<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    /**
     * @return int
     */
    public function count(): int
    {
        $qb = $this->createQueryBuilder('m');

        return $qb->select('count(m.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
